# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import pacs.utils


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingCandidateCommittees',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('candidate_name', models.TextField(null=True, blank=True)),
                ('committee_id', models.IntegerField(null=True, blank=True)),
                ('committee_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('election_office', models.TextField(null=True, blank=True)),
                ('phone', models.TextField(null=True, blank=True)),
                ('party_affiliation', models.TextField(null=True, blank=True)),
                ('web_address', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'working_candidate_committees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingCandidateFilings',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('election_txt', models.TextField(null=True, blank=True)),
                ('election_year', models.IntegerField(null=True, blank=True)),
                ('office_group', models.TextField(null=True, blank=True)),
                ('id_nbr', models.IntegerField(null=True, blank=True)),
                ('office', models.TextField(null=True, blank=True)),
                ('candidate_office', models.TextField(null=True, blank=True)),
                ('candidate_file_rsn', models.IntegerField(null=True, blank=True)),
                ('file_mthd_ind', models.TextField(null=True, blank=True)),
                ('filetype_descr', models.TextField(null=True, blank=True)),
                ('party_descr', models.TextField(null=True, blank=True)),
                ('major_party_ind', models.TextField(null=True, blank=True)),
                ('cand_ballot_name_txt', models.TextField(null=True, blank=True)),
                ('occptn_txt', models.TextField(null=True, blank=True)),
                ('education_bckgrnd_txt', models.TextField(null=True, blank=True)),
                ('occptn_bkgrnd_txt', models.TextField(null=True, blank=True)),
                ('school_grade_diploma_degree_certificate_course_of_study', models.TextField(null=True, blank=True)),
                ('prev_govt_bkgrnd_txt', models.TextField(null=True, blank=True)),
                ('judge_incbnt_ind', models.TextField(null=True, blank=True)),
                ('qlf_ind', models.TextField(null=True, blank=True)),
                ('filed_date', models.DateField(null=True, blank=True)),
                ('file_fee_rfnd_date', models.DateField(null=True, blank=True)),
                ('witdrw_date', models.DateField(null=True, blank=True)),
                ('withdrw_resn_txt', models.NullBooleanField()),
                ('pttn_file_date', models.DateField(null=True, blank=True)),
                ('pttn_sgnr_rqd_nbr', models.IntegerField(null=True, blank=True)),
                ('pttn_signr_filed_nbr', models.IntegerField(null=True, blank=True)),
                ('pttn_cmplt_date', models.DateField(null=True, blank=True)),
                ('ballot_order_nbr', models.IntegerField(null=True, blank=True)),
                ('prfx_name_cd', models.TextField(null=True, blank=True)),
                ('first_name', models.TextField(null=True, blank=True)),
                ('mdle_name', models.TextField(null=True, blank=True)),
                ('last_name', models.TextField(null=True, blank=True)),
                ('sufx_name', models.TextField(null=True, blank=True)),
                ('title_txt', models.TextField(null=True, blank=True)),
                ('mailing_addr_line_1', models.TextField(null=True, blank=True)),
                ('mailing_addr_line_2', models.TextField(null=True, blank=True)),
                ('mailing_city_name', models.TextField(null=True, blank=True)),
                ('mailing_st_cd', models.TextField(null=True, blank=True)),
                ('mailing_zip_code', models.IntegerField(null=True, blank=True)),
                ('mailing_zip_plus_four', models.IntegerField(null=True, blank=True)),
                ('residence_addr_line_1', models.TextField(null=True, blank=True)),
                ('residence_addr_line_2', models.TextField(null=True, blank=True)),
                ('residence_city_name', models.TextField(null=True, blank=True)),
                ('residence_st_cd', models.TextField(null=True, blank=True)),
                ('residence_zip_code', models.IntegerField(null=True, blank=True)),
                ('residence_zip_plus_four', models.IntegerField(null=True, blank=True)),
                ('home_phone', models.TextField(null=True, blank=True)),
                ('cell_phone', models.TextField(null=True, blank=True)),
                ('fax_phone', models.TextField(null=True, blank=True)),
                ('email', models.TextField(null=True, blank=True)),
                ('work_phone', models.TextField(null=True, blank=True)),
                ('web_address', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'working_candidate_filings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingCommittees',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('committee_id', models.IntegerField(null=True, blank=True)),
                ('committee_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('committee_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('committee_subtype', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('party_affiliation', models.TextField(null=True, blank=True)),
                ('phone', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('election_office', models.TextField(null=True, blank=True)),
                ('candidate_name', models.TextField(null=True, blank=True)),
                ('candidate_email_address', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('candidate_work_phone_home_phone_fax', models.TextField(null=True, blank=True)),
                ('candidate_address', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('treasurer_name', models.TextField(null=True, blank=True)),
                ('treasurer_work_phone_home_phone_fax', models.TextField(null=True, blank=True)),
                ('treasurer_mailing_address', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('web_address', models.TextField(null=True, blank=True)),
                ('measure', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('simple_election', models.TextField(null=True, blank=True)),
                ('db_update_status', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'working_committees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingTransactions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tran_id', models.IntegerField(null=True, blank=True)),
                ('tran_date', models.DateField(null=True, blank=True)),
                ('filer', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('contributor_payee', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('sub_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('amount', models.FloatField(null=True, blank=True)),
                ('contributor_payee_committee_id', models.IntegerField(null=True, blank=True)),
                ('filer_id', models.IntegerField(null=True, blank=True)),
                ('purp_desc', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('book_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('addr_line1', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('filed_date', models.DateField(null=True, blank=True)),
                ('addr_line2', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('city', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('state', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('zip', models.IntegerField(null=True, blank=True)),
                ('purpose_codes', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('direction', models.CharField(max_length=7, null=True, blank=True)),
                ('contributor_payee_class', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
            ],
            options={
                'db_table': 'working_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignDetail',
            fields=[
                ('filer_id', models.IntegerField(default=0, help_text='2384 unique integers identifying each committee.', serialize=False, primary_key=True)),
                ('candidate_name', models.TextField(help_text='Not unique_together (candidate_name, committee_name, race).', null=True, blank=True)),
                ('committee_name', pacs.utils.LongCharField(help_text='Nonunique identifying name.', max_length=1000000000, null=True, blank=True)),
                ('race', models.TextField(null=True, blank=True)),
                ('website', models.TextField(null=True, blank=True)),
                ('phone', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
                ('total_spent', models.FloatField(null=True, blank=True)),
                ('grassroots', models.FloatField(null=True, blank=True)),
                ('instate', models.FloatField(null=True, blank=True)),
                ('election', models.TextField(null=True, blank=True)),
                ('party', models.TextField(null=True, blank=True)),
                ('num_transactions', models.BigIntegerField(null=True, blank=True)),
                ('committee_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('committee_subtype', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('db_update_status', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'campaign_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CcWorkingTransactions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tran_id', models.IntegerField(null=True, blank=True)),
                ('tran_date', models.DateField(null=True, blank=True)),
                ('filer', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('contributor_payee', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('sub_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('amount', models.FloatField(null=True, blank=True)),
                ('contributor_payee_committee_id', models.IntegerField(null=True, blank=True)),
                ('filer_id', models.IntegerField(null=True, blank=True)),
                ('purp_desc', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('book_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('addr_line1', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('filed_date', models.DateField(null=True, blank=True)),
                ('addr_line2', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('city', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('state', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('zip', models.IntegerField(null=True, blank=True)),
                ('purpose_codes', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('direction', models.CharField(max_length=7, null=True, blank=True)),
                ('contributor_payee_class', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
            ],
            options={
                'db_table': 'cc_working_transactions',
                'managed': True,
            },
        ),
    ]
