# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import pacs.utils


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('committee_id', models.IntegerField(null=True, blank=True)),
                ('date', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'access_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcGrassRootsInState',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('filer_id', models.FloatField(null=True, blank=True)),
                ('filer', models.TextField(null=True, blank=True)),
                ('candidate_name', models.TextField(null=True, blank=True)),
                ('total_money', models.FloatField(null=True, blank=True)),
                ('percent_grassroots', models.FloatField(null=True, blank=True)),
                ('percent_instate', models.FloatField(null=True, blank=True)),
                ('total_money_out', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'ac_grass_roots_in_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllOregonSum',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('in_field', models.FloatField(null=True, db_column='in', blank=True)),
                ('out', models.FloatField(null=True, blank=True)),
                ('from_within', models.FloatField(null=True, blank=True)),
                ('to_within', models.FloatField(null=True, blank=True)),
                ('from_outside', models.FloatField(null=True, blank=True)),
                ('to_outside', models.FloatField(null=True, blank=True)),
                ('total_grass_roots', models.FloatField(null=True, blank=True)),
                ('total_from_in_state', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'all_oregon_sum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('candidate_name', models.TextField(null=True, blank=True)),
                ('committee_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('race', models.TextField(null=True, blank=True)),
                ('website', models.TextField(null=True, blank=True)),
                ('phone', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
                ('total_spent', models.FloatField(null=True, blank=True)),
                ('grassroots', models.FloatField(null=True, blank=True)),
                ('instate', models.FloatField(null=True, blank=True)),
                ('filer_id', models.IntegerField(null=True, blank=True)),
                ('election', models.TextField(null=True, blank=True)),
                ('party', models.TextField(null=True, blank=True)),
                ('num_transactions', models.BigIntegerField(null=True, blank=True)),
                ('committee_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('committee_subtype', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('db_update_status', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'campaign_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateByState',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('candidate_name', models.TextField(null=True, blank=True)),
                ('filer_id', models.IntegerField(null=True, blank=True)),
                ('state', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('direction', models.CharField(max_length=7, null=True, blank=True)),
                ('value', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'candidate_by_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateSumByDate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('filer_id', models.IntegerField(null=True, blank=True)),
                ('tran_date', models.DateField(null=True, blank=True)),
                ('total_in', models.FloatField(null=True, blank=True)),
                ('total_out', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'candidate_sum_by_date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CcGrassRootsInState',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('filer_id', models.IntegerField(null=True, blank=True)),
                ('filer', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('num_transactions', models.BigIntegerField(null=True, blank=True)),
                ('in_state', models.FloatField(null=True, blank=True)),
                ('grass_roots', models.FloatField(null=True, blank=True)),
                ('total_contributions', models.FloatField(null=True, blank=True)),
                ('total_money', models.FloatField(null=True, blank=True)),
                ('total_money_out', models.FloatField(null=True, blank=True)),
                ('percent_grass_roots', models.FloatField(null=True, blank=True)),
                ('percent_in_state', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'cc_grass_roots_in_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CcWorkingTransactions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tran_id', models.IntegerField(null=True, blank=True)),
                ('tran_date', models.DateField(null=True, blank=True)),
                ('filer', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('contributor_payee', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('sub_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('amount', models.FloatField(null=True, blank=True)),
                ('contributor_payee_committee_id', models.IntegerField(null=True, blank=True)),
                ('filer_id', models.IntegerField(null=True, blank=True)),
                ('purp_desc', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('book_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('addr_line1', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('filed_date', models.DateField(null=True, blank=True)),
                ('addr_line2', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('city', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('state', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('zip', models.IntegerField(null=True, blank=True)),
                ('purpose_codes', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('direction', models.CharField(max_length=7, null=True, blank=True)),
                ('contributor_payee_class', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
            ],
            options={
                'db_table': 'cc_working_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirectionCodes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sub_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('direction', models.CharField(max_length=7, null=True, blank=True)),
            ],
            options={
                'db_table': 'direction_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('title', models.TextField(null=True, blank=True)),
                ('endpoint_name', models.TextField(null=True, blank=True)),
                ('txt', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'documentation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HackOregonDbStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ac_grass_roots_in_state', models.FloatField(null=True, blank=True)),
                ('campaign_detail', models.FloatField(null=True, blank=True)),
                ('candidate_by_state', models.FloatField(null=True, blank=True)),
                ('candidate_sum_by_date', models.FloatField(null=True, blank=True)),
                ('cc_grass_roots_in_state', models.FloatField(null=True, blank=True)),
                ('cc_working_transactions', models.FloatField(null=True, blank=True)),
                ('direction_codes', models.FloatField(null=True, blank=True)),
                ('raw_candidate_filings', models.FloatField(null=True, blank=True)),
                ('raw_committees', models.FloatField(null=True, blank=True)),
                ('raw_committees_scraped', models.FloatField(null=True, blank=True)),
                ('raw_committee_transactions', models.FloatField(null=True, blank=True)),
                ('raw_committee_transactions_ammended_transactions', models.FloatField(null=True, blank=True)),
                ('state_translation', models.FloatField(null=True, blank=True)),
                ('working_candidate_committees', models.FloatField(null=True, blank=True)),
                ('working_candidate_filings', models.FloatField(null=True, blank=True)),
                ('working_committees', models.FloatField(null=True, blank=True)),
                ('working_transactions', models.FloatField(null=True, blank=True)),
                ('date', models.DateField(null=True, blank=True)),
                ('event_at_log_time', models.TextField(null=True, blank=True)),
                ('hack_oregon_db_status', models.FloatField(null=True, blank=True)),
                ('all_oregon_sum', models.FloatField(null=True, blank=True)),
                ('state_sum_by_date', models.FloatField(null=True, blank=True)),
                ('documentation', models.FloatField(null=True, blank=True)),
                ('oregon_by_contributions', models.FloatField(null=True, blank=True)),
                ('oregon_by_purpose_codes', models.FloatField(null=True, blank=True)),
                ('sub_type_from_contributor_payee', models.FloatField(null=True, blank=True)),
                ('oregon_committee_agg', models.FloatField(null=True, blank=True)),
                ('import_dates', models.FloatField(null=True, blank=True)),
                ('raw_committee_transactions_errors', models.FloatField(null=True, blank=True)),
                ('access_log', models.FloatField(null=True, blank=True)),
                ('search_log', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'hack_oregon_db_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImportDates',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('file_id', models.DecimalField(null=True, max_digits=256, decimal_places=256, blank=True)),
                ('scrape_date', models.DateField(null=True, blank=True)),
                ('file_name', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'import_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OregonByContributions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('contribution_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'oregon_by_contributions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OregonByPurposeCodes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('purpose_code', models.TextField(null=True, blank=True)),
                ('total', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'oregon_by_purpose_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OregonCommitteeAgg',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('contributor_payee', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('contributor_payee_committee_id', models.IntegerField(null=True, blank=True)),
                ('sum', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'oregon_committee_agg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PacsCommitteetransactions',
            fields=[
                ('tran_id', models.IntegerField(serialize=False, primary_key=True)),
                ('original_id', models.IntegerField()),
                ('tran_date', models.DateField(null=True, blank=True)),
                ('tran_status', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('filer', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('contributor_payee', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('sub_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('amount', models.FloatField(null=True, blank=True)),
                ('aggregate_amount', models.FloatField(null=True, blank=True)),
                ('contributor_payee_committee_id', models.IntegerField(null=True, blank=True)),
                ('filer_id', models.IntegerField(null=True, blank=True)),
                ('attest_by_name', pacs.utils.LongCharField(max_length=1000000000)),
                ('attest_date', models.DateField()),
                ('review_by_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('review_date', models.DateField(null=True, blank=True)),
                ('due_date', models.DateField(null=True, blank=True)),
                ('occptn_ltr_date', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('pymt_sched_txt', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('purp_desc', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('intrst_rate', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('check_nbr', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('tran_stsfd_ind', models.NullBooleanField()),
                ('filed_by_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('filed_date', models.DateField(null=True, blank=True)),
                ('addr_book_agent_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('book_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('title_txt', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('occptn_txt', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('emp_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('emp_city', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('emp_state', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('employ_ind', models.NullBooleanField()),
                ('self_employ_ind', models.NullBooleanField()),
                ('addr_line1', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('addr_line2', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('city', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('state', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('zip', models.IntegerField(null=True, blank=True)),
                ('zip_plus_four', models.IntegerField(null=True, blank=True)),
                ('county', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('purpose_codes', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('exp_date', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
            ],
            options={
                'db_table': 'pacs_committeetransactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawCandidateFilings',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('election_txt', models.TextField(null=True, blank=True)),
                ('election_year', models.IntegerField(null=True, blank=True)),
                ('office_group', models.TextField(null=True, blank=True)),
                ('id_nbr', models.IntegerField(null=True, blank=True)),
                ('office', models.TextField(null=True, blank=True)),
                ('candidate_office', models.TextField(null=True, blank=True)),
                ('candidate_file_rsn', models.IntegerField(null=True, blank=True)),
                ('file_mthd_ind', models.TextField(null=True, blank=True)),
                ('filetype_descr', models.TextField(null=True, blank=True)),
                ('party_descr', models.TextField(null=True, blank=True)),
                ('major_party_ind', models.TextField(null=True, blank=True)),
                ('cand_ballot_name_txt', models.TextField(null=True, blank=True)),
                ('occptn_txt', models.TextField(null=True, blank=True)),
                ('education_bckgrnd_txt', models.TextField(null=True, blank=True)),
                ('occptn_bkgrnd_txt', models.TextField(null=True, blank=True)),
                ('school_grade_diploma_degree_certificate_course_of_study', models.TextField(null=True, blank=True)),
                ('prev_govt_bkgrnd_txt', models.TextField(null=True, blank=True)),
                ('judge_incbnt_ind', models.TextField(null=True, blank=True)),
                ('qlf_ind', models.TextField(null=True, blank=True)),
                ('filed_date', models.DateField(null=True, blank=True)),
                ('file_fee_rfnd_date', models.DateField(null=True, blank=True)),
                ('witdrw_date', models.DateField(null=True, blank=True)),
                ('withdrw_resn_txt', models.NullBooleanField()),
                ('pttn_file_date', models.DateField(null=True, blank=True)),
                ('pttn_sgnr_rqd_nbr', models.IntegerField(null=True, blank=True)),
                ('pttn_signr_filed_nbr', models.IntegerField(null=True, blank=True)),
                ('pttn_cmplt_date', models.DateField(null=True, blank=True)),
                ('ballot_order_nbr', models.IntegerField(null=True, blank=True)),
                ('prfx_name_cd', models.TextField(null=True, blank=True)),
                ('first_name', models.TextField(null=True, blank=True)),
                ('mdle_name', models.TextField(null=True, blank=True)),
                ('last_name', models.TextField(null=True, blank=True)),
                ('sufx_name', models.TextField(null=True, blank=True)),
                ('title_txt', models.TextField(null=True, blank=True)),
                ('mailing_addr_line_1', models.TextField(null=True, blank=True)),
                ('mailing_addr_line_2', models.TextField(null=True, blank=True)),
                ('mailing_city_name', models.TextField(null=True, blank=True)),
                ('mailing_st_cd', models.TextField(null=True, blank=True)),
                ('mailing_zip_code', models.IntegerField(null=True, blank=True)),
                ('mailing_zip_plus_four', models.IntegerField(null=True, blank=True)),
                ('residence_addr_line_1', models.TextField(null=True, blank=True)),
                ('residence_addr_line_2', models.TextField(null=True, blank=True)),
                ('residence_city_name', models.TextField(null=True, blank=True)),
                ('residence_st_cd', models.TextField(null=True, blank=True)),
                ('residence_zip_code', models.IntegerField(null=True, blank=True)),
                ('residence_zip_plus_four', models.IntegerField(null=True, blank=True)),
                ('home_phone', models.TextField(null=True, blank=True)),
                ('cell_phone', models.TextField(null=True, blank=True)),
                ('fax_phone', models.TextField(null=True, blank=True)),
                ('email', models.TextField(null=True, blank=True)),
                ('work_phone', models.TextField(null=True, blank=True)),
                ('web_address', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'raw_candidate_filings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawCommittees',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('committee_id', models.IntegerField(null=True, blank=True)),
                ('committee_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('committee_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('committee_subtype', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('candidate_office', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('candidate_office_group', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('filing_date', models.DateField(null=True, blank=True)),
                ('organization_filing_date', models.DateField(null=True, db_column='organization_filing Date', blank=True)),
                ('treasurer_first_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('treasurer_last_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('treasurer_mailing_address', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('treasurer_work_phone', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('treasurer_fax', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('candidate_first_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('candidate_last_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('candidate_maling_address', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('candidate_work_phone', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('candidate_residence_phone', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('candidate_fax', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('candidate_email', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('active_election', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('measure', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
            ],
            options={
                'db_table': 'raw_committees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawCommitteesScraped',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('committee_id', models.IntegerField(null=True, blank=True)),
                ('name', models.TextField(null=True, blank=True)),
                ('acronym', models.TextField(null=True, blank=True)),
                ('pac_type', models.TextField(null=True, blank=True)),
                ('filing_effective_from', models.TextField(null=True, blank=True)),
                ('filing_type', models.TextField(null=True, blank=True)),
                ('address', models.TextField(null=True, blank=True)),
                ('campaign_phone', models.TextField(null=True, blank=True)),
                ('treasurer_name', models.TextField(null=True, blank=True)),
                ('treasurer_mailing_address', models.TextField(null=True, blank=True)),
                ('treasurer_work_phone_home_phone_fax', models.TextField(null=True, blank=True)),
                ('treasurer_email_address', models.TextField(null=True, blank=True)),
                ('candidate_name', models.TextField(null=True, blank=True)),
                ('candidate_election_office', models.TextField(null=True, blank=True)),
                ('candidate_party_affiliation', models.TextField(null=True, blank=True)),
                ('candidate_candidate_address', models.TextField(null=True, blank=True)),
                ('candidate_work_phone_home_phone_fax', models.TextField(null=True, blank=True)),
                ('candidate_mailing_address', models.TextField(null=True, blank=True)),
                ('candidate_email_address', models.TextField(null=True, blank=True)),
                ('candidate_occupation', models.TextField(null=True, blank=True)),
                ('candidate_employer', models.TextField(null=True, blank=True)),
                ('measure_election', models.TextField(null=True, blank=True)),
                ('measure_support', models.TextField(null=True, blank=True)),
                ('measure_details', models.TextField(null=True, blank=True)),
                ('committee_type', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'raw_committees_scraped',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawCommitteeTransactions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tran_id', models.IntegerField(null=True, blank=True)),
                ('original_id', models.IntegerField(null=True, blank=True)),
                ('tran_date', models.DateField(null=True, blank=True)),
                ('tran_status', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('filer', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('contributor_payee', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('sub_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('amount', models.FloatField(null=True, blank=True)),
                ('aggregate_amount', models.FloatField(null=True, blank=True)),
                ('contributor_payee_committee_id', models.IntegerField(null=True, blank=True)),
                ('filer_id', models.IntegerField(null=True, blank=True)),
                ('attest_by_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('attest_date', models.DateField(null=True, blank=True)),
                ('review_by_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('review_date', models.DateField(null=True, blank=True)),
                ('due_date', models.DateField(null=True, blank=True)),
                ('occptn_ltr_date', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('pymt_sched_txt', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('purp_desc', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('intrst_rate', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('check_nbr', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('tran_stsfd_ind', models.NullBooleanField()),
                ('filed_by_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('filed_date', models.DateField(null=True, blank=True)),
                ('addr_book_agent_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('book_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('title_txt', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('occptn_txt', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('emp_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('emp_city', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('emp_state', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('employ_ind', models.NullBooleanField()),
                ('self_employ_ind', models.NullBooleanField()),
                ('addr_line1', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('addr_line2', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('city', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('state', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('zip', models.IntegerField(null=True, blank=True)),
                ('zip_plus_four', models.IntegerField(null=True, blank=True)),
                ('county', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('purpose_codes', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('exp_date', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
            ],
            options={
                'db_table': 'raw_committee_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawCommitteeTransactionsAmmendedTransactions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tran_id', models.IntegerField(null=True, blank=True)),
                ('original_id', models.IntegerField(null=True, blank=True)),
                ('tran_date', models.DateField(null=True, blank=True)),
                ('tran_status', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('filer', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('contributor_payee', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('sub_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('amount', models.FloatField(null=True, blank=True)),
                ('aggregate_amount', models.FloatField(null=True, blank=True)),
                ('contributor_payee_committee_id', models.IntegerField(null=True, blank=True)),
                ('filer_id', models.IntegerField(null=True, blank=True)),
                ('attest_by_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('attest_date', models.DateField(null=True, blank=True)),
                ('review_by_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('review_date', models.DateField(null=True, blank=True)),
                ('due_date', models.DateField(null=True, blank=True)),
                ('occptn_ltr_date', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('pymt_sched_txt', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('purp_desc', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('intrst_rate', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('check_nbr', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('tran_stsfd_ind', models.NullBooleanField()),
                ('filed_by_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('filed_date', models.DateField(null=True, blank=True)),
                ('addr_book_agent_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('book_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('title_txt', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('occptn_txt', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('emp_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('emp_city', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('emp_state', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('employ_ind', models.NullBooleanField()),
                ('self_employ_ind', models.NullBooleanField()),
                ('addr_line1', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('addr_line2', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('city', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('state', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('zip', models.IntegerField(null=True, blank=True)),
                ('zip_plus_four', models.IntegerField(null=True, blank=True)),
                ('county', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('purpose_codes', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('exp_date', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
            ],
            options={
                'db_table': 'raw_committee_transactions_ammended_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawCommitteeTransactionsErrors',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tran_id', models.IntegerField(null=True, blank=True)),
                ('original_id', models.IntegerField(null=True, blank=True)),
                ('tran_date', models.DateField(null=True, blank=True)),
                ('tran_status', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('filer', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('contributor_payee', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('sub_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('amount', models.FloatField(null=True, blank=True)),
                ('aggregate_amount', models.FloatField(null=True, blank=True)),
                ('contributor_payee_committee_id', models.IntegerField(null=True, blank=True)),
                ('filer_id', models.IntegerField(null=True, blank=True)),
                ('attest_by_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('attest_date', models.DateField(null=True, blank=True)),
                ('review_by_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('review_date', models.DateField(null=True, blank=True)),
                ('due_date', models.DateField(null=True, blank=True)),
                ('occptn_ltr_date', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('pymt_sched_txt', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('purp_desc', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('intrst_rate', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('check_nbr', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('tran_stsfd_ind', models.NullBooleanField()),
                ('filed_by_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('filed_date', models.DateField(null=True, blank=True)),
                ('addr_book_agent_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('book_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('title_txt', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('occptn_txt', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('emp_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('emp_city', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('emp_state', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('employ_ind', models.NullBooleanField()),
                ('self_employ_ind', models.NullBooleanField()),
                ('addr_line1', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('addr_line2', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('city', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('state', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('zip', models.IntegerField(null=True, blank=True)),
                ('zip_plus_four', models.IntegerField(null=True, blank=True)),
                ('county', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('purpose_codes', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('exp_date', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
            ],
            options={
                'db_table': 'raw_committee_transactions_errors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('search_term', models.TextField(null=True, blank=True)),
                ('date', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'search_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateSumByDate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tran_date', models.DateField(null=True, blank=True)),
                ('total_in', models.FloatField(null=True, blank=True)),
                ('total_out', models.FloatField(null=True, blank=True)),
                ('total_from_within', models.FloatField(null=True, blank=True)),
                ('total_to_within', models.FloatField(null=True, blank=True)),
                ('total_from_the_outside', models.FloatField(null=True, blank=True)),
                ('total_to_the_outside', models.FloatField(null=True, blank=True)),
                ('total_grass_roots', models.FloatField(null=True, blank=True)),
                ('total_from_in_state', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'state_sum_by_date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateTranslation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('statefull', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('abbreviation', models.CharField(max_length=3, null=True, blank=True)),
            ],
            options={
                'db_table': 'state_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubTypeFromContributorPayee',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('contributor_payee', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
            ],
            options={
                'db_table': 'sub_type_from_contributor_payee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingCandidateCommittees',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('candidate_name', models.TextField(null=True, blank=True)),
                ('committee_id', models.IntegerField(null=True, blank=True)),
                ('committee_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('election_office', models.TextField(null=True, blank=True)),
                ('phone', models.TextField(null=True, blank=True)),
                ('party_affiliation', models.TextField(null=True, blank=True)),
                ('web_address', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'working_candidate_committees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingCandidateFilings',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('election_txt', models.TextField(null=True, blank=True)),
                ('election_year', models.IntegerField(null=True, blank=True)),
                ('office_group', models.TextField(null=True, blank=True)),
                ('id_nbr', models.IntegerField(null=True, blank=True)),
                ('office', models.TextField(null=True, blank=True)),
                ('candidate_office', models.TextField(null=True, blank=True)),
                ('candidate_file_rsn', models.IntegerField(null=True, blank=True)),
                ('file_mthd_ind', models.TextField(null=True, blank=True)),
                ('filetype_descr', models.TextField(null=True, blank=True)),
                ('party_descr', models.TextField(null=True, blank=True)),
                ('major_party_ind', models.TextField(null=True, blank=True)),
                ('cand_ballot_name_txt', models.TextField(null=True, blank=True)),
                ('occptn_txt', models.TextField(null=True, blank=True)),
                ('education_bckgrnd_txt', models.TextField(null=True, blank=True)),
                ('occptn_bkgrnd_txt', models.TextField(null=True, blank=True)),
                ('school_grade_diploma_degree_certificate_course_of_study', models.TextField(null=True, blank=True)),
                ('prev_govt_bkgrnd_txt', models.TextField(null=True, blank=True)),
                ('judge_incbnt_ind', models.TextField(null=True, blank=True)),
                ('qlf_ind', models.TextField(null=True, blank=True)),
                ('filed_date', models.DateField(null=True, blank=True)),
                ('file_fee_rfnd_date', models.DateField(null=True, blank=True)),
                ('witdrw_date', models.DateField(null=True, blank=True)),
                ('withdrw_resn_txt', models.NullBooleanField()),
                ('pttn_file_date', models.DateField(null=True, blank=True)),
                ('pttn_sgnr_rqd_nbr', models.IntegerField(null=True, blank=True)),
                ('pttn_signr_filed_nbr', models.IntegerField(null=True, blank=True)),
                ('pttn_cmplt_date', models.DateField(null=True, blank=True)),
                ('ballot_order_nbr', models.IntegerField(null=True, blank=True)),
                ('prfx_name_cd', models.TextField(null=True, blank=True)),
                ('first_name', models.TextField(null=True, blank=True)),
                ('mdle_name', models.TextField(null=True, blank=True)),
                ('last_name', models.TextField(null=True, blank=True)),
                ('sufx_name', models.TextField(null=True, blank=True)),
                ('title_txt', models.TextField(null=True, blank=True)),
                ('mailing_addr_line_1', models.TextField(null=True, blank=True)),
                ('mailing_addr_line_2', models.TextField(null=True, blank=True)),
                ('mailing_city_name', models.TextField(null=True, blank=True)),
                ('mailing_st_cd', models.TextField(null=True, blank=True)),
                ('mailing_zip_code', models.IntegerField(null=True, blank=True)),
                ('mailing_zip_plus_four', models.IntegerField(null=True, blank=True)),
                ('residence_addr_line_1', models.TextField(null=True, blank=True)),
                ('residence_addr_line_2', models.TextField(null=True, blank=True)),
                ('residence_city_name', models.TextField(null=True, blank=True)),
                ('residence_st_cd', models.TextField(null=True, blank=True)),
                ('residence_zip_code', models.IntegerField(null=True, blank=True)),
                ('residence_zip_plus_four', models.IntegerField(null=True, blank=True)),
                ('home_phone', models.TextField(null=True, blank=True)),
                ('cell_phone', models.TextField(null=True, blank=True)),
                ('fax_phone', models.TextField(null=True, blank=True)),
                ('email', models.TextField(null=True, blank=True)),
                ('work_phone', models.TextField(null=True, blank=True)),
                ('web_address', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'working_candidate_filings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingCommittees',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('committee_id', models.IntegerField(null=True, blank=True)),
                ('committee_name', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('committee_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('committee_subtype', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('party_affiliation', models.TextField(null=True, blank=True)),
                ('phone', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('election_office', models.TextField(null=True, blank=True)),
                ('candidate_name', models.TextField(null=True, blank=True)),
                ('candidate_email_address', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('candidate_work_phone_home_phone_fax', models.TextField(null=True, blank=True)),
                ('candidate_address', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('treasurer_name', models.TextField(null=True, blank=True)),
                ('treasurer_work_phone_home_phone_fax', models.TextField(null=True, blank=True)),
                ('treasurer_mailing_address', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('web_address', models.TextField(null=True, blank=True)),
                ('measure', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('simple_election', models.TextField(null=True, blank=True)),
                ('db_update_status', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'working_committees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingTransactions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tran_id', models.IntegerField(null=True, blank=True)),
                ('tran_date', models.DateField(null=True, blank=True)),
                ('filer', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('contributor_payee', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('sub_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('amount', models.FloatField(null=True, blank=True)),
                ('contributor_payee_committee_id', models.IntegerField(null=True, blank=True)),
                ('filer_id', models.IntegerField(null=True, blank=True)),
                ('purp_desc', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('book_type', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('addr_line1', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('filed_date', models.DateField(null=True, blank=True)),
                ('addr_line2', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('city', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('state', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('zip', models.IntegerField(null=True, blank=True)),
                ('purpose_codes', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
                ('direction', models.CharField(max_length=7, null=True, blank=True)),
                ('contributor_payee_class', pacs.utils.LongCharField(max_length=1000000000, null=True, blank=True)),
            ],
            options={
                'db_table': 'working_transactions',
                'managed': False,
            },
        ),
    ]
