# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_year', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song_bow',
            name='confidence',
            field=models.FloatField(blank=True, default=0.3),
            preserve_default=False,
        ),
    ]
