# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_year', '0002_song_bow_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='song_bow',
            name='prob_dict_by_decade',
            field=models.TextField(blank=True),
        ),
    ]
