# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict_year', '0003_song_bow_prob_dict_by_decade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song_bow',
            old_name='prob_dict_by_decade',
            new_name='prob_decades',
        ),
    ]
